### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by mo-hobbs** [learn-co-curriculum/phase-3-ruby-oo-class-variables-introduction#1]
### Canvas Link

https://learning.flatironschool.com/courses/4551/pages/introduction-to-class-variables-and-class-methods?module_item_id=344976

### Concern

I dont think this link works anymore - says server cant be found http://rubylearning.com/satishtalim/ruby_names.html 

its the last link on the page in the sentence: 
If at any point you need a refresher on different types of Ruby variables, check this blog post (Links to an external site.).

### Additional Context

![Screen Shot 2021-12-15 at 10 44 51 AM](https://user-images.githubusercontent.com/79115095/146218024-9a007ac9-66d0-48ee-96f2-51fc12f49
![Screen Shot 2021-12-15 at 10 44 45 AM](https://user-images.githubusercontent.com/79115095/146218028-24c33486-5946-4a5f-8100-c4a9315dbe0f.png)
1e1.png)

**Comment by lizbur10** [comment]
Hi @fortfreedom3 ! Thanks for flagging this - the broken link has been replaced 💙
